apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
  labels:
    app: {{ .Values.db.appLabel }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.db.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.appLabel }}
    spec:
      containers:
        - name: {{ .Values.db.containerName }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: {{ .Values.db.volumeName }}
              mountPath: {{ .Values.db.mountPath }}
      volumes:
        - name: {{ .Values.db.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.db.pvcName }}
