apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.pvcName }}
spec:
  accessModes:
    - {{ .Values.db.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.db.pvc.storage }}
