apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
spec:
  selector:
    app: {{ .Values.db.appLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.port }}
  type: {{ .Values.db.service.type }}
